### ISSUE TITLE
Makefile: fix install

### ISSUE THREAD

**Issue by Benevolent** [Benevolent/media-inventory-manager#1]
calling mediainv does not seem to work after running make all

**Comment by RyanCPeters** [comment]
I'm trying to reproduce the problem, but when I call `make all` in bash, everything appears to be running correctly. 

Any tips on how I might otherwise verify this?

**Comment by Benevolent** [comment]
does calling mediainv work from the command line? if so can you please post the output of ``` $ whereis mediainv ``` ?

**Comment by RyanCPeters** [comment]
```sh
~/GitHub_remotes/media-inventory-manager$ make all
g++  -Isrc -O2  -c -o src/hashtable.o src/hashtable.cpp
g++  -Isrc -O2  -c -o src/main.o src/main.cpp
g++  -Isrc -O2    src/hashtable.o src/main.o -o mediainv
g++ tests/alltests.cpp -o test; ./test
[+] Running all tests -
~/GitHub_remotes/media-inventory-manager$ whereis mediainv
mediainv:
```

**Comment by Benevolent** [comment]
given your whereis output it looks like your system cannot find mediainv.
I have added dummy output to the dummy main.cpp, please pull the changes, recompile, and re make all. If you recieve output from running                  ```$ mediainv ``` then it is working, otherwise your system is not telling you that it is not finding the mediainv executable.

Please post the output of running the new executable, and for the record please give me details about your system, what OS/distro is this?

**Comment by RyanCPeters** [comment]
```sh
~/GitHub_remotes/media-inventory-manager$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
~/GitHub_remotes/media-inventory-manager$ make all
g++  -Isrc -O2  -c -o src/hashtable.o src/hashtable.cpp
g++  -Isrc -O2  -c -o src/main.o src/main.cpp
g++  -Isrc -O2    src/hashtable.o src/main.o -o mediainv
g++ tests/alltests.cpp -o test; ./test
[+] Running all tests -
~/GitHub_remotes/media-inventory-manager$ whereis mediainv
mediainv:
```

**Comment by RyanCPeters** [comment]
Found the problem, the Makefile just needed to include the phony `install` as a prerequisite to the `all :` rule.

**Comment by Benevolent** [comment]
Closed this issue as we have fixed this
